name: Execute Exercises

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Day
    strategy:
      matrix:
        days: [1, 2]
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
      name: Install Dependencies
    - run: npm run tsc
      name: Compile TypeScript
    - run: node lib/day${{ matrix.days }}/index.js
      name: Execute Exercise
