name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: do exercises
    strategy:
      matrix:
        days: [1, 2]
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
      name: install deps
    - run: npm run tsc
      name: compile
    - run: node lib day${{ matrix.days }}/index.js
      name: run exercise
